package ru.savefood.shop;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Deletes files created by a failed multipart lot request.  A deletion that
 * cannot complete is recorded after the failed transaction rolls back, then
 * retried by the scheduler.  The queue accepts only filenames generated by
 * {@link ru.savefood.upload.UploadService}, so it can never target another path.
 */
@Service
public class LotUploadCleanup {

    private static final Logger log = Logger.getLogger(LotUploadCleanup.class.getName());
    private static final String GENERATED_IMAGE = "[a-f0-9]{32}\\.(jpg|jpeg|png)";

    private final JdbcTemplate jdbc;
    private final Path uploadDir;

    public LotUploadCleanup(JdbcTemplate jdbc,
                            @Value("${savefood.shop-upload-dir}") String uploadDir) {
        this.jdbc = jdbc;
        this.uploadDir = Paths.get(uploadDir).toAbsolutePath().normalize();
    }

    /** Attempt deletion immediately; retain only failures for a durable retry. */
    public void removeOrQueue(List<String> filenames) {
        if (filenames == null || filenames.isEmpty()) {
            return;
        }
        List<String> failed = filenames.stream().filter(name -> !delete(name)).toList();
        if (failed.isEmpty()) {
            return;
        }
        if (TransactionSynchronizationManager.isSynchronizationActive()) {
            TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
                @Override
                public void afterCompletion(int status) {
                    failed.forEach(LotUploadCleanup.this::queueFailure);
                }
            });
        } else {
            failed.forEach(this::queueFailure);
        }
    }

    @Scheduled(fixedDelay = 15 * 60_000, initialDelay = 60_000)
    public void retryPending() {
        List<Map<String, Object>> rows;
        try {
            rows = jdbc.queryForList("SELECT id, filename FROM shop_upload_cleanup "
                + "WHERE completed_at IS NULL AND next_attempt_at <= CURRENT_TIMESTAMP ORDER BY id LIMIT 100");
        } catch (RuntimeException e) {
            log.warning("[shop-upload-cleanup] unable to load cleanup queue: " + e.getMessage());
            return;
        }
        for (Map<String, Object> row : rows) {
            long id = ((Number) row.get("id")).longValue();
            String filename = (String) row.get("filename");
            if (delete(filename)) {
                jdbc.update("UPDATE shop_upload_cleanup SET attempts = attempts + 1, "
                    + "last_attempt_at = CURRENT_TIMESTAMP, last_error = NULL, completed_at = CURRENT_TIMESTAMP "
                    + "WHERE id = ? AND completed_at IS NULL", id);
            } else {
                jdbc.update("UPDATE shop_upload_cleanup SET attempts = attempts + 1, "
                    + "last_attempt_at = CURRENT_TIMESTAMP, last_error = 'delete failed', "
                    + "next_attempt_at = CURRENT_TIMESTAMP + make_interval(mins => LEAST(1440, (attempts + 1) * 15)) "
                    + "WHERE id = ? AND completed_at IS NULL", id);
            }
        }
    }

    private boolean delete(String filename) {
        Path path = safePath(filename);
        if (path == null) {
            return false;
        }
        try {
            Files.deleteIfExists(path);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void queueFailure(String filename) {
        try {
            jdbc.update("INSERT INTO shop_upload_cleanup (filename, last_error) VALUES (?, 'delete failed') "
                + "ON CONFLICT (filename) DO UPDATE SET completed_at = NULL, next_attempt_at = CURRENT_TIMESTAMP, "
                + "last_error = EXCLUDED.last_error", filename);
        } catch (RuntimeException e) {
            log.severe("[shop-upload-cleanup] orphan could not be queued for retry: " + filename + ": "
                + e.getMessage());
        }
    }

    private Path safePath(String filename) {
        if (filename == null || !filename.matches(GENERATED_IMAGE)) {
            return null;
        }
        Path candidate = uploadDir.resolve(filename).normalize();
        return candidate.getParent() != null && candidate.getParent().equals(uploadDir) ? candidate : null;
    }
}
