-- Failed multipart lot creation may need a filesystem retry after its database
-- transaction rolls back.  Only random filenames generated by UploadService are stored.
CREATE TABLE public.shop_upload_cleanup (
    id bigserial PRIMARY KEY,
    filename text NOT NULL UNIQUE,
    attempts integer NOT NULL DEFAULT 0,
    last_attempt_at timestamp with time zone,
    next_attempt_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error text,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT shop_upload_cleanup_filename_format
        CHECK (filename ~ '^[a-f0-9]{32}\.(jpg|jpeg|png)$')
);
